### ISSUE TITLE
Can't parse a complex expression

### ISSUE THREAD

**Issue by ronnycsharp** [sys27/xFunc#185]
Hi,

I can't parse such a expression "im(5i+40°)".
It throws an error. "An error occurred while parsing the tree.".
Perhaps I shouldn't use the dev-branch at the moment.

Regards
Ronny

**Comment by ronnycsharp** [comment]
It also doesn't work with your master-version v3.3.

**Comment by sys27** [comment]
@ronnycsharp Hi.
im(5i+40°): the root cause is in lexer, regex matches + (plus sign) as a part of complex number, but should be simple addition.
10i∠30°: I think it's not an issue (just need to display more information error message), because ∠ symbol require the following format {number}∠{degree}. So,

**Comment by ronnycsharp** [comment]
Hi Dmitry,
sorry it was my issue. The complex expression should look like 5+20° not 5i+20° ^^.

Kind regards
Ronny
