### ISSUE TITLE
Can't execute "cos(sqrt(x+sqrt(x)))"

### ISSUE THREAD

**Issue by ronnycsharp** [sys27/xFunc#189]
Hi Dmitry,

I've seen that I can't execute the following expression, "cos(sqrt(x+sqrt(x)))".
If I execute only the argument "sqrt(x+sqrt(x))" than it returns the right complex number.
The cos-function should work with a complex expression.
I don't know what's wrong here.

Regards
Ronny

**Comment by sys27** [comment]
This issue is related to Type Check (usage of ResultType property). 'Quick Fix' is remove type checking from parser and all expressions, but I don't want to do it. I think I should somehow rework it (+ add ability to extent it).

**Comment by sys27** [comment]
#151 should fix this issue, because the 'Execute' method of Add function won't be rely on ResultType property and will return right objects.

**Comment by sys27** [comment]
The main problem is that _Sqrt_ return type is equal to _Number_ or _ComplexNumber_ (always, no matter, which parameter is passed to it, the result type can be calculated only on execute-time). So, when we try to add _Sqrt_ to any number, the add function will select _ComplexNumber_ as result type. And it's ok, because, _Number + ComplexNumber = ComplexNumber_. But in case of 'cos' function, it's is not ok, because it will try to convert complex number to double (this conversion can be partially fixed by #151, see previous comment, but we will still have strange behavior: _ResultType = ComplexNumber, Actual Type = double_).

**Comment by sys27** [comment]
Maybe, we should introduce mechanism to disable type checking only for specified function by attribute (eg. [DisableTypeCheck]) or custom result type (eg. `class NoResultType : IResultType`)
