### ISSUE TITLE
Issue with Matrix * Vector - Multiplication

### ISSUE THREAD

**Issue by ronnycsharp** [sys27/xFunc#202]
Hi Dmitry,

probably there is an issue with the calculation of such an expression, like "{{1,2},{3,4}}*{5,6}".
It throws an exception with invalid matrix size, but the result should be {17,39}.

Regards
Ronny

**Comment by sys27** [comment]
The latest dev version doesn't throw an exception, but it still returns wrong result '{{23, 34}}'.

**Comment by sys27** [comment]
It's expected behaviour.

[Matrix Multiplication Wiki](https://en.wikipedia.org/wiki/Matrix_multiplication):
> For matrix multiplication, **the number of columns** in the first matrix must be equal to **the number of rows** in the second matrix. The result matrix, known as the matrix product, has the number of rows of the first and the number of columns of the second matrix.

`{{1,2},{3,4}}` has 2 rows and 2 columns.
`{5,6}` represents just a vector, it has 1 row and 2 column.

Right input for xFunc: `{{1,2},{3,4}} * {{5}, {6}}`

`{{5}, {6}}` represents a matrix with 2 rows and 1 column.
